build: false

environment:
  matrix:
    - PY27:
      PYTHON: "C:\\Python27-x64"
      RUBY_VERSION: "22"
    - PY35:
      PYTHON: "C:\\Python35-x64"
      RUBY_VERSION: "22"

services:
  - postgresql93

init:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - SET PATH=C:\Ruby22\bin;%PATH%
  - ruby -v
  - gem -v
  - SET PGUSER=stalker_admin
  - SET PGPASSWORD=stalker
  - SET PATH=C:\Program Files\PostgreSQL\9.3\bin\;%PATH%
  - psql --version

install:
  - gem install mime-types -v 2.6.2  # Required to install taskjuggler
  - gem install taskjuggler
  - "%PYTHON%/Scripts/pip.exe install sqlalchemy psycopg2 jinja2 alembic mako markupsafe python-editor nose coverage"
  - createdb stalker_test

test_script:
  - nosetests --verbosity=1 --cover-erase --with-coverage --cover-package=stalker
