build: false

environment:
  matrix:
    - PY27:
      PYTHON: "C:\\Python27-x64"
      RUBY_VERSION: "22-x64"
    - PY35:
      PYTHON: "C:\\Python35-x64"
      RUBY_VERSION: "22"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

services:
  - postgresql93

install:
  - SET PGUSER=stalker_admin
  - SET PGPASSWORD=stalker
  - PATH=C:\Program Files\PostgreSQL\9.3\bin\;%PATH%
  - gem install mime-types -v 2.6.2  # Required to install taskjuggler
  - gem install taskjuggler
  - "%PYTHON%/Scripts/pip.exe install sqlalchemy psycopg2 jinja2 alembic mako markupsafe python-editor nose coverage"

before_test:
  - python --version
  - ruby -v
  - gem -v

build_script:
  - createdb stalker_test

test_script:
  - nosetests --verbosity=1 --cover-erase --with-coverage --cover-package=stalker
